[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://capable-dodol-8182cd.netlify.app"
  NODE_VERSION = "18"

[build.processing]
  skip_processing = false
  css = { bundle = true, minify = true }
  js = { bundle = true, minify = true }
  images = { compress = true }
  html = { pretty_urls = true }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-nextjs"] 