[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"

[[headers]]
  for = "/_next/static/css/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/_next/static/chunks/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/_next/static/js/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/_next/static/media/*.woff2"
  [headers.values]
    Content-Type = "font/woff2"

[[headers]]
  for = "/_next/static/media/*.woff"
  [headers.values]
    Content-Type = "font/woff"

[[headers]]
  for = "/_next/static/media/*.ttf"
  [headers.values]
    Content-Type = "font/ttf"

[[headers]]
  for = "/_next/static/media/*.png"
  [headers.values]
    Content-Type = "image/png"

[[headers]]
  for = "/_next/static/media/*.jpg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/_next/static/media/*.jpeg"
  [headers.values]
    Content-Type = "image/jpeg"

[[headers]]
  for = "/_next/static/media/*.gif"
  [headers.values]
    Content-Type = "image/gif"

[[headers]]
  for = "/_next/static/media/*.svg"
  [headers.values]
    Content-Type = "image/svg+xml"

[[headers]]
  for = "/_next/static/media/*.webp"
  [headers.values]
    Content-Type = "image/webp"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

# Plugin kaldırıldı - standalone Next.js için gerekli değil