services:
  - type: web
    name: alo17-socket
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install
    startCommand: node socket-server.js
    envVars:
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_FRONTEND_URL
        value: https://mq4nym7p6b1.netlify.app
    healthCheckPath: /
    autoDeploy: true 