services:
  - type: web
    name: alo17-nextjs
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_URL
        value: https://alo17-nextjs.onrender.com
      - key: NEXT_PUBLIC_API_URL
        value: https://alo17-nextjs.onrender.com
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true 