services:
  - type: web
    name: alo17
    env: node
    buildCommand: npm install && prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:postgres@localhost:5432/alo17
      - key: NEXTAUTH_SECRET
        value: alo17_secret_key_2024
      - key: NEXTAUTH_URL
        value: https://alo17.onrender.com
      - key: GOOGLE_CLIENT_ID
        value: your_google_client_id
      - key: GOOGLE_CLIENT_SECRET
        value: your_google_client_secret
      - key: APPLE_ID
        value: your_apple_id
      - key: APPLE_SECRET
        value: your_apple_secret 