name: Deploy Alo17 to Render

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        
    - name: Deploy to Render
      run: |
        echo "Build completed successfully!"
        echo "Deploying to Render..."
        echo "Render will automatically deploy from GitHub repository"
        echo "Deployment URL: https://alo17-new-27-06.onrender.com"
        
    - name: Notify deployment
      run: |
        echo "✅ Alo17 successfully deployed to Render!"
        echo "🌐 Live URL: https://alo17-new-27-06.onrender.com"
        echo "🔧 Admin Panel: https://alo17-new-27-06.onrender.com/admin"
